### PR TITLE
Fix width and height swap on image create.

### PR DESCRIPTION
**Pull request by btolsch**
Makes rectangular icons work.

### CODE REVIEW

**Comment by ashinkarov** [comment]
The change looks sane, but I would like to try it out before I merge it.

**Comment by btolsch** [comment]
Here's an icon that I'm using this with in case you don't already have one to test with.
[wide_icon.zip](https://github.com/ashinkarov/i3-extras/files/147840/wide_icon.zip) (github made me zip the xbm)

**Comment by btolsch** [comment]
This is the [documentation](http://xcb-util.sourcearchive.com/documentation/0.3.3-2/group__xcb____image__t_g1a6c3a8a81c94d86baa28b7cba0a3ff5.html) for the function being affected as well, in case that helps.  This should make it clearer that width and height should be swapped.

**Comment by ashinkarov** [comment]
Yup, the change makes perfect sense.  Sorry it took me so long, it was a busy month.
Merging it :)

**Pull request merged**
